# Generated by Django 4.2.1 on 2023-06-14 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(choices=[('Cédula de Identidad', 'Cédula de Identidad'), ('Licencia de Conducir', 'Licencia de Conducir'), ('Padrón', 'Padrón'), ('Permiso de Circulación', 'Permiso de Circulación'), ('Revisión Técnica', 'Revisión Técnica'), ('SOAP', 'SOAP')], max_length=50)),
                ('link_doc', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
